name: Deploy Chrome Extension

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.json'
      - 'newtab/**'
      - 'background.js'
      - 'icons/**'

jobs:
  build-and-deploy:
    uses: ravitejakamalapuram/.github-workflows-shared/.github/workflows/chrome-extension-cd.yml@v1.1.2
    with:
      extension-dir: '.'
    secrets:
      chrome-extension-id: ${{ secrets.APP_ID }}
      chrome-client-id: ${{ secrets.CLIENT_ID }}
      chrome-client-secret: ${{ secrets.CLIENT_SECRET }}
      chrome-refresh-token: ${{ secrets.REFRESH_TOKEN }}
